"""plan recurring discount

Revision ID: 794d3b3fcf7c
Revises: 2caae01d3691
Create Date: 2026-06-06 10:03:18.446183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794d3b3fcf7c'
down_revision: Union[str, Sequence[str], None] = '2caae01d3691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('recurring_discount_type', sa.String(length=20), server_default='NONE', nullable=False))
    op.add_column('plans', sa.Column('recurring_discount_value', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'recurring_discount_value')
    op.drop_column('plans', 'recurring_discount_type')
    # ### end Alembic commands ###
