# Generated by Django 6.0.6 on 2026-06-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_oneoffrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=128)),
                ('hmac_secret', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
