# Generated by Django 6.0.6 on 2026-06-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_servicecredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('order_id', models.CharField(blank=True, max_length=128)),
                ('subscribe_id', models.CharField(blank=True, max_length=64)),
                ('desc', models.TextField(blank=True)),
                ('payload', models.JSONField()),
                ('verified', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
