"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-only-insecure")

DEBUG = os.environ.get("DEBUG", "True") == "True"  # 데모 전용 — 배포 시 False

# 결제 서버(별도 docker)가 알림을 POST할 때 Host 헤더가 host.docker.internal 이 되므로
# 허용 목록에 포함한다(없으면 Django가 400 DisallowedHost로 거부 → 알림 수신 실패).
# 외부 접근용 도메인/IP는 환경변수 ALLOWED_HOSTS(콤마 구분)로 추가한다.
#   예: ALLOWED_HOSTS=api-stg-pay.medisolveai.com   ("*" 를 넣으면 전체 허용 — 데모 한정)
ALLOWED_HOSTS = ["127.0.0.1", "localhost", "host.docker.internal", "sample"] + [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]

# CSRF 신뢰 origin — 외부에서 폼(구독·결제·카드 POST)을 제출하면 Django 4+는 Origin이
# 이 목록에 있어야 통과시킨다(없으면 403 CSRF). 스킴+호스트[:포트] 형태로, 환경변수
# CSRF_TRUSTED_ORIGINS(콤마 구분)로 외부 접속 origin을 넘긴다.
#   예: CSRF_TRUSTED_ORIGINS=http://api-stg-pay.medisolveai.com:8001
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]

# https 프록시(nginx 등) 뒤에 있을 때 원 스킴을 X-Forwarded-Proto 헤더로 인식한다
# → request.is_secure()·보안 쿠키·CSRF 검증이 실제 스킴과 정합.
# (현재 nginx 8001 통과 프록시는 평문 http라 영향 없음. 추후 443 TLS 경유 시 정상 동작.)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",  # 금액 천단위 콤마(intcomma) 표시용
    "shop",
]

# 데모 — admin/auth 미사용이므로 관련 미들웨어 제거
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [{
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [],
    "APP_DIRS": True,
    "OPTIONS": {"context_processors": [
        "django.template.context_processors.request",
        "django.contrib.messages.context_processors.messages",
        # 활성 서비스명을 모든 템플릿에 주입 — base.html 내비 표시용
        "shop.context.active_service",
    ]},
}]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# SQLite 파일 경로 — 기본은 프로젝트 폴더(개발). Docker에서는 SQLITE_PATH로 볼륨 경로를 주어
# 컨테이너를 내려도(down) 데이터가 유지되게 한다(예: /app/data/db.sqlite3 ← named volume).
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("SQLITE_PATH") or (BASE_DIR / "db.sqlite3"),
    }
}


# messages를 세션 기반으로 (auth 미들웨어 없음)
MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"


# Internationalization
LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"

# 구독서버 연동
PAYMENT_API_BASE = os.environ.get("PAYMENT_API_BASE", "http://127.0.0.1:8000")
SERVICE_API_KEY = os.environ.get("SERVICE_API_KEY", "")
SERVICE_HMAC_SECRET = os.environ.get("SERVICE_HMAC_SECRET", "")
TOSS_CLIENT_KEY = os.environ.get("TOSS_CLIENT_KEY", "")
