"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-only-insecure")

DEBUG = os.environ.get("DEBUG", "True") == "True"  # 데모 전용 — 배포 시 False

# 결제 서버(별도 docker)가 알림을 POST할 때 Host 헤더가 host.docker.internal 이 되므로
# 허용 목록에 포함한다(없으면 Django가 400 DisallowedHost로 거부 → 알림 수신 실패).
# 추가 호스트는 환경변수 ALLOWED_HOSTS(콤마 구분)로 덮어쓸 수 있다.
ALLOWED_HOSTS = ["127.0.0.1", "localhost", "host.docker.internal", "sample"] + [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",  # 금액 천단위 콤마(intcomma) 표시용
    "shop",
]

# 데모 — admin/auth 미사용이므로 관련 미들웨어 제거
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [{
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [],
    "APP_DIRS": True,
    "OPTIONS": {"context_processors": [
        "django.template.context_processors.request",
        "django.contrib.messages.context_processors.messages",
        # 활성 서비스명을 모든 템플릿에 주입 — base.html 내비 표시용
        "shop.context.active_service",
    ]},
}]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# SQLite 파일 경로 — 기본은 프로젝트 폴더(개발). Docker에서는 SQLITE_PATH로 볼륨 경로를 주어
# 컨테이너를 내려도(down) 데이터가 유지되게 한다(예: /app/data/db.sqlite3 ← named volume).
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("SQLITE_PATH") or (BASE_DIR / "db.sqlite3"),
    }
}


# messages를 세션 기반으로 (auth 미들웨어 없음)
MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"


# Internationalization
LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"

# 구독서버 연동
PAYMENT_API_BASE = os.environ.get("PAYMENT_API_BASE", "http://127.0.0.1:8000")
SERVICE_API_KEY = os.environ.get("SERVICE_API_KEY", "")
SERVICE_HMAC_SECRET = os.environ.get("SERVICE_HMAC_SECRET", "")
TOSS_CLIENT_KEY = os.environ.get("TOSS_CLIENT_KEY", "")
